name: Deploy to AWS[Beta]
run-name: ${{ github.actor }} is testing out GitHub Actions üöÄ
on: [push]
permissions: read-all
env:
  service: service-a service-b
jobs:
  deploy_to_aws_using_serverlessFramework:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@master
      - name: checkout branch
        run: git checkout github_action
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "üçè This job's status is ${{ job.status }}."
      - name: add nodejs environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: check node version
        run: node -v
      - name: Cache node modules
        id: npmCache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package.json') }}
      - if: ${{ steps.npmCache.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: install serverless
        run: |
          pwd
          npm install -g serverless
          npm install -D @serverless/compose
          npm install -D serverless-layers
      - name: serverless deploy
        id: serverless-deploy
        run: sls deploy --stage beta
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - if: ${{ success() }}
        run: echo "${{ github.triggering_actor }} the workflow success"
      #      - name: serverless deploy test
#        uses: hdev14/sls-deploy-action@main
#        with:
#          awsAccessKeyID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          stage: 'beta'
#          region: 'us-east-1'
      - run: echo "This job's status is ${{ job.status }}"
